// apps/web/src/svelte-viz/components/ConnectionStatus.svelte
<script lang="ts">
  let { isConnected }: { isConnected: boolean } = $props()
</script>

<div
  class="connection-status"
  data-connected={isConnected}
  role="status"
  aria-live="polite"
>
  <span class="connection-status-indicator"></span>
  {isConnected ? 'Live Stream' : 'Connecting...'}
</div>

// apps/web/src/react-viz/components/connection-status.tsx
import type { UseSSEStreamOutput } from '../hooks/use-sse-stream'

export function ConnectionStatus({
  isConnected,
}: Pick<UseSSEStreamOutput, 'isConnected'>) {
  return (
    <div
      className="connection-status"
      data-connected={isConnected}
      role="status"
      aria-live="polite"
    >
      <span className="connection-status-indicator" />
      {isConnected ? 'Live Stream' : 'Connecting...'}
    </div>
  )
}
