// apps/web/src/vue-viz/components/Dashboard.vue
<script setup lang="ts">
import { useStreamService } from '../composables/use-stream-service'
import SocialEventCard from './social-event-card.vue'
import ConnectionStatus from './connection-status.vue'
import { SOCIAL_MEDIAS } from '@upfluence/core'

const state = useStreamService()
</script>

<template>
  <main class="dashboard-container">
    <header class="dashboard-header">
      <div>
        <h1 class="dashboard-title">Upfluence Live Stream - Vue</h1>
        <p class="dashboard-subtitle">
          Real-time social media events visualization
        </p>
      </div>

      <div class="dashboard-status-container">
        <div class="dashboard-metrics">
          <div class="dashboard-rate">
            {{ state.eventsPerSecond }} events/sec
          </div>
          <div>{{ state.totalEvents.toLocaleString() }} total</div>
        </div>
        <ConnectionStatus :isConnected="state.isConnected" />
      </div>
    </header>

    <div class="dashboard-grid">
      <SocialEventCard
        v-for="socialMedia in SOCIAL_MEDIAS"
        :key="socialMedia"
        :socialMedia="socialMedia"
        :count="state.totals[socialMedia] ?? 0"
        :weekdayHourlyCount="state.accumulator[socialMedia] ?? {}"
      />
    </div>
  </main>
</template>

// apps/web/src/react-viz/components/dashboard.tsx
import { useStreamService } from '../hooks/use-stream-service'
import { SocialEventCard } from './social-event-card'
import { ConnectionStatus } from './connection-status'
import { SOCIAL_MEDIAS } from '@upfluence/core'

export function Dashboard() {
  const {
    isConnected,
    accumulator,
    totals,
    eventsPerSecond,
    totalEvents = 0,
  } = useStreamService()

  return (
    <main className="dashboard-container">
      <header className="dashboard-header">
        <div>
          <h1 className="dashboard-title">Upfluence Live Stream</h1>
          <p className="dashboard-subtitle">
            Real-time social media events visualization
          </p>
        </div>

        <div className="dashboard-status-container">
          <div className="dashboard-metrics">
            <div className="dashboard-rate">{eventsPerSecond} events/sec</div>
            <div>{totalEvents.toLocaleString()} total</div>
          </div>
          <ConnectionStatus isConnected={isConnected} />
        </div>
      </header>

      <div className="dashboard-grid">
        {SOCIAL_MEDIAS.map((type) => (
          <SocialEventCard
            key={type}
            socialMedia={type}
            count={totals[type] ?? 0}
            weekdayHourlyCount={accumulator[type] ?? {}}
          />
        ))}
      </div>
    </main>
  )
}
