// apps/web/src/svelte-viz/components/ErrorFallback.svelte
<script lang="ts">
  let {
    error,
    resetErrorBoundary,
  }: { error: Error; resetErrorBoundary: () => void } = $props()
</script>

<div class="error-fallback" role="alert">
  <h2>Something went wrong.</h2>
  <p>{error.message}</p>
  <button onclick={resetErrorBoundary}>Try again</button>
</div>

// apps/web/src/react-viz/components/error-fallback.tsx
export function ErrorFallback({
  error,
  resetErrorBoundary,
}: {
  error: Error
  resetErrorBoundary: () => void
}) {
  return (
    <div className="error-fallback" role="alert">
      <h2>Something went wrong.</h2>
      <p>{error.message}</p>
      <button onClick={resetErrorBoundary}>Try again</button>
    </div>
  )
}
