// apps/web/src/svelte-viz/components/social-event-card.svelte
<script lang="ts">
  import WeeklyCalendarGraph from './weekly-calendar-graph.svelte'
  import {
    SOCIAL_MEDIA_TEXT_MAP,
    type SocialMedias,
    type WeekdayHourlyCount,
  } from '@upfluence/core'

  let {
    socialMedia,
    count,
    weekdayHourlyCount,
  }: {
    socialMedia: SocialMedias
    count: number
    weekdayHourlyCount: WeekdayHourlyCount
  } = $props()
</script>

<article class="social-event-card" data-social={socialMedia}>
  <header class="social-event-header">
    <h2 class="social-event-title">
      {SOCIAL_MEDIA_TEXT_MAP[socialMedia]}
    </h2>
    <data class="social-event-count" value={count}>
      {count}
    </data>
  </header>
  <WeeklyCalendarGraph {weekdayHourlyCount} />
</article>

// apps/web/src/react-viz/components/social-event-card.tsx
import { WeeklyCalendarGraph } from './weekly-calendar-graph'
import {
  SOCIAL_MEDIA_TEXT_MAP,
  type SocialMedias,
  type WeekdayHourlyCount,
} from '@upfluence/core'

export function SocialEventCard({
  socialMedia,
  count,
  weekdayHourlyCount,
}: Props) {
  return (
    <article className="social-event-card" data-social={socialMedia}>
      <header className="social-event-header">
        <h3 className="social-event-title">
          {SOCIAL_MEDIA_TEXT_MAP[socialMedia]}
        </h3>
        <data className="social-event-count" value={count}>
          {count}
        </data>
      </header>
      <WeeklyCalendarGraph weekdayHourlyCount={weekdayHourlyCount} />
    </article>
  )
}

type Props = {
  socialMedia: SocialMedias
  count: number
  weekdayHourlyCount: WeekdayHourlyCount
}
