// apps/web/src/svelte-viz/app.svelte
<svelte:options runes={true} />

<script lang="ts">
  import Dashboard from './components/dashboard.svelte'
  import ErrorFallback from './components/error-fallback.svelte'
</script>

<svelte:boundary>
  <Dashboard />
  {#snippet failed(error, reset)}
    <ErrorFallback error={error as Error} resetErrorBoundary={reset} />
  {/snippet}
</svelte:boundary>

// apps/react-viz/src/App.tsx
import { ErrorFallback } from './components/error-fallback'
import { Dashboard } from './components/dashboard'
import { ErrorBoundary } from 'react-error-boundary'

function App() {
  return (
    <ErrorBoundary FallbackComponent={ErrorFallback}>
      <Dashboard />
    </ErrorBoundary>
  )
}

export default App
