// apps/web/src/svelte-viz/components/ConnectionStatus.svelte
<script lang="ts">
  let { isConnected }: { isConnected: boolean } = $props()
</script>

<div
  class="connection-status"
  data-connected={isConnected}
  role="status"
  aria-live="polite"
>
  <span class="connection-status-indicator"></span>
  {isConnected ? 'Live Stream' : 'Connecting...'}
</div>

// apps/web/src/vue-viz/components/ConnectionStatus.vue
<script setup lang="ts">
defineProps<{
  isConnected: boolean
}>()
</script>

<template>
  <div
    class="connection-status"
    :data-connected="isConnected"
    role="status"
    aria-live="polite"
  >
    <span class="connection-status-indicator" />
    {{ isConnected ? 'Live Stream' : 'Connecting...' }}
  </div>
</template>
