// apps/web/src/react-viz/components/error-fallback.tsx
export function ErrorFallback({
  error,
  resetErrorBoundary,
}: {
  error: Error
  resetErrorBoundary: () => void
}) {
  return (
    <div className="error-fallback" role="alert">
      <h2>Something went wrong.</h2>
      <p>{error.message}</p>
      <button onClick={resetErrorBoundary}>Try again</button>
    </div>
  )
}

// apps/web/src/vue-viz/components/ErrorFallback.vue
<script setup lang="ts">
defineProps<{
  error: Error
  resetErrorBoundary: () => void
}>()
</script>

<template>
  <div class="error-fallback" role="alert">
    <h2>Something went wrong.</h2>
    <p>{{ error.message }}</p>
    <button @click="resetErrorBoundary">Try again</button>
  </div>
</template>
