// apps/react-viz/src/App.tsx
import { ErrorFallback } from './components/error-fallback'
import { Dashboard } from './components/dashboard'
import { ErrorBoundary } from 'react-error-boundary'

function App() {
  return (
    <ErrorBoundary FallbackComponent={ErrorFallback}>
      <Dashboard />
    </ErrorBoundary>
  )
}

export default App

// apps/web/src/svelte-viz/App.svelte
<script lang="ts">
  import Dashboard from './components/Dashboard.svelte'
  import ErrorFallback from './components/ErrorFallback.svelte'
</script>

<svelte:boundary>
  <Dashboard />
  {#snippet failed(error, reset)}
    <ErrorFallback {error} resetErrorBoundary={reset} />
  {/snippet}
</svelte:boundary>
