// apps/web/src/vue-viz/App.vue
<script setup lang="ts">
import { ref, onErrorCaptured } from 'vue'
import Dashboard from './components/dashboard.vue'
import ErrorFallback from './components/error-fallback.vue'

const error = ref<Error | null>(null)

onErrorCaptured((err) => {
  error.value = err instanceof Error ? err : new Error(String(err))
  return false // prevent propagation
})

const resetErrorBoundary = () => {
  error.value = null
}
</script>

<template>
  <ErrorFallback
    v-if="error"
    :error="error"
    :resetErrorBoundary="resetErrorBoundary"
  />
  <Dashboard v-else />
</template>

// apps/web/src/svelte-viz/app.svelte
<svelte:options runes={true} />

<script lang="ts">
  import Dashboard from './components/dashboard.svelte'
  import ErrorFallback from './components/error-fallback.svelte'
</script>

<svelte:boundary>
  <Dashboard />
  {#snippet failed(error, reset)}
    <ErrorFallback error={error as Error} resetErrorBoundary={reset} />
  {/snippet}
</svelte:boundary>
