// apps/react-viz/src/components/connection-status.tsx
import React from 'react'

type Props = {
  isConnected: boolean
}

export const ConnectionStatus: React.FC<Props> = ({ isConnected }) => {
  return (
    <div
      className="connection-status"
      data-connected={isConnected}
      role="status"
      aria-live="polite"
    >
      <span className="connection-status-indicator" />
      {isConnected ? 'Live Stream' : 'Connecting...'}
    </div>
  )
}

// apps/web/src/svelte-viz/components/ConnectionStatus.svelte
<script lang="ts">
  let { isConnected }: { isConnected: boolean } = $props()
</script>

<div
  class="connection-status"
  data-connected={isConnected}
  role="status"
  aria-live="polite"
>
  <span class="connection-status-indicator"></span>
  {isConnected ? 'Live Stream' : 'Connecting...'}
</div>
